---
- hosts: 172.31.42.193
  become: yes
  tasks:
  - name: execute a linux command
    command: hostname -f
    register: myresult

  - name: to display first task result
    debug:
       msg: "{{myresult}}"
       verbosity: 3

  - name: install git
    apt:
       name: git
       state: present
    when: myresult.stderr !=""

  - name: install tree
    apt:
       name: tree
       state: present
    when: myresult.stderr ==""