---
- hosts: 172.31.42.193
  become: yes
  tasks:
  - include_tasks: myfile.yml

  - name: Copy the file into ansible nodes
    copy: 
       src: staticfile
       dest: /home/sai/mystaticfile.txt

  - name: Replace the web server home page
    template:
      src: index.j2
      dest: /var/www/html/index.html 
      