---
- hosts: 172.31.42.193
  become: yes
  tasks:
  - include_tasks: myfile.yml

  - name: Copy the file into ansible nodes
    copy: 
       src: staticfile
       dest: /home/sai/mystaticfile.txt

  - name: Replace the web server home page
    template:
      src: index.j2
      dest: /var/www/html/index.html 
    notify: Restart web server

       
  - name: Download an internet file
    get_url:
         url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
         dest: /home/sai/jenkins.io.key
         force_basic_auth: yes

  handlers:
  - name: Restart web server
    service:
       name: wget
       state: restarted