--- 
- hosts: 172.31.42.193
  become: yes
  tasks: 
  - name: install webserver
    apt: 
       name: apache2
       state: present 

  - name: install tree 
    apt: 
       name: tree
       stateee: present
       ignore_errors: true  

  - name: install wget
    apt: 
       name: wget
       state: present 
