---
- hosts: myWebservers
  become: yes
  tasks:
  - name: install web server on ubuntu
    apt:
      name: "{{Webpackonubuntu}}"
      state: present
    when: ansible_os_family =="Debian"


  - name: webserver service start
    service:
        name: "{{Webpackonubuntu}}"
        state: restarted
    when: ansible_os_family =="Debian"
     
  - name: install httpd server on Redhat
    yum:
       name: "{{WebpackonRedhat}}"
       state: present
    when: ansible_os_family =="RedHat"
     
  - name: starting httpd webserver on Redhat
    service:
         name: "{{WebpackonRedhat}}"
         state: started
    when: ansible_os_family =="RedHat"