---
- hosts: all
  become: yes
  tasks:
  - name: install web server
    apt:
      name: apache2
      state: present
    when: ansible_os_family =="Debian"


  - name: webserver service start
    service:
        name: apache2
        state: restarted
    when: ansible_os_family =="Debian"
     
  - name: install httpd server on redhat
    yum:
       name: httpd
       state: present
    when: ansible_os_family =="RedHat"
     
  - name: starting httpd webserver on Redhat
    service:
         name: httpd
         state: started
    when: ansible_os_family =="RedHat"